# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: 20241230-101900-genteel-spot

language: es

pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 2
  max_ngram: 4
- name: DIETClassifier
  epochs: 120
  batch_strategy: sequence
  learning_rate: 0.002
  constrain_similarities: true
- name: ResponseSelector
  epochs: 150
  constrain_similarities: true
- name: FallbackClassifier
  threshold: 0.3
  ambiguity_threshold: 0.1

# Configuration for Rasa Core.=
policies:
- name: RulePolicy
- name: TEDPolicy
  max_history: 3
  epochs: 80
  constrain_similarities: true
