version: "3.9"

services:
  rasa-core:
    image: rasa/rasa:3.6.2-full
    container_name: rasa-core
    ports:
      - "5005:5005"  # Puerto donde escucha Rasa Core HTTP API
    volumes:
      - ./:/app  # ruta donde se encuentra el proyecto de Rasa
    command: >
      run
      --enable-api
      --cors "*"
      --endpoints endpoints.yml
      --port 5005
    depends_on:
      - rasa-actions
    networks:
      - rasa-network

  rasa-actions:
    build:
      context: ./actions  # Carpeta donde está el Dockerfile y el código de acciones
    container_name: rasa-actions
    ports:
      - "5055:5055"  # Puerto por defecto del action server
    networks:
      - rasa-network

networks:
  rasa-network:
    driver: bridge
